apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-dep
  labels:
    app: nginx0-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx0
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx:1.7.9
        ports:
        - containerPort: 80
